# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_stream": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://openmusickit.github.io/music21utils/"

git_url = "https://github.com/openmusickit/music21utils/tree/master/"

def custom_doc_links(name): return None
